language: node_js
node_js:
  - node
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - echo 'Build starting...'
        - echo 'Installing dependencies...'
        - yarn
        - echo 'Running unit tests...'
        - yarn test
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
